services:
  storage: # сервис с именем storage
    image: redis # используется образ redis:latest
    volumes:
      - ./data:/data # подключает диск

  counter: 
    image: abtank/counter:v2.0.1
    ports:
      - 3002:3002 
    environment:
    - PORT=3002 
    - STORAGE_URL=redis://storage
    depends_on:
      -  storage 

  bookstore:
    build: .
    ports:
      - 80:3000
    depends_on:
      -  counter 
    environment:
      - COUNTER_URL=http://counter:3002